import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Header } from '@/components/Header'
import { Main } from '@/components/Main'
import { Footer } from '@/components/Footer'
import { useCounter } from '@/libs/utils/useCounter'
import { useInputArray } from '@/libs/utils/useInputArray'
import { useBgLightBlue } from '@/libs/utils/useBgLightBlue'

export default function Home() {
  const { count, handleCount } = useCounter()
  const { text, isShow, array, handleDisplay, handleChange, handleAdd } =
    useInputArray()
  useBgLightBlue()

  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />

      <div className={styles.content}>
        {isShow ? (
          <div>
            <label htmlFor='input'>name</label>
            <input
              id='input'
              type='text'
              value={text}
              onChange={handleChange}
            />
            <button onClick={handleAdd}>追加</button>
          </div>
        ) : null}
        <ul>
          {array.map((item) => {
            return <li key={item}>{item}</li>
          })}
        </ul>
        <button onClick={handleDisplay}>{isShow ? '非表示' : '表示'}</button>

        <h1>{count}</h1>
        <button onClick={handleCount}>カウントアップ</button>
      </div>
      <Main page='index' />
      <Footer />
    </div>
  )
}
