import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Header } from '@/components/Header'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page Test</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <h1 className={styles.content}>Next.jsで学ぶReact.js講座</h1>
    </div>
  )
}
